import type { Migration } from './index.js';
import { tableExists } from './schemaChecks.js';

export const Migration001_BaselineSchema: Migration = {
  id: '001',
  name: 'baseline_schema_2026_02',
  up: async (adapter) => {
    if (await tableExists(adapter, 'users')) {
      console.log('ℹ️  Baseline schema already present; skipping');
      return;
    }
    await adapter.execute('SET FOREIGN_KEY_CHECKS = 0');
    try {
      await adapter.execute("CREATE TABLE `activity_log` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `actor_user_id` int NOT NULL,\n  `site_id` int DEFAULT NULL,\n  `action` varchar(100) NOT NULL,\n  `summary` varchar(500) NOT NULL,\n  `metadata_json` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  KEY `idx_activity_log_actor_created` (`actor_user_id`,`created_at`),\n  KEY `idx_activity_log_site_created` (`site_id`,`created_at`),\n  KEY `idx_activity_log_created` (`created_at`),\n  CONSTRAINT `fk_activity_log_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_activity_log_site` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `app_settings` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `key` varchar(255) NOT NULL,\n  `value` text NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `key` (`key`),\n  KEY `idx_app_settings_key` (`key`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `cable_types` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_cable_type_name` (`site_id`,`name`),\n  KEY `idx_cable_types_site_id` (`site_id`),\n  CONSTRAINT `fk_cable_types_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `invitation_sites` (\n  `invitation_id` int NOT NULL,\n  `site_id` int NOT NULL,\n  `site_role` varchar(50) NOT NULL,\n  KEY `idx_invitation_sites_invitation` (`invitation_id`),\n  KEY `idx_invitation_sites_site` (`site_id`),\n  CONSTRAINT `fk_invitation_sites_invitation_id` FOREIGN KEY (`invitation_id`) REFERENCES `invitations` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_invitation_sites_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `invitations` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `token_hash` varchar(255) NOT NULL,\n  `email` varchar(255) NOT NULL,\n  `invited_by` int NOT NULL,\n  `expires_at` timestamp(3) NOT NULL,\n  `used_at` timestamp(3) NULL DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `username` varchar(100) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `token_hash` (`token_hash`),\n  KEY `fk_invitations_invited_by` (`invited_by`),\n  KEY `idx_invitations_email` (`email`),\n  KEY `idx_invitations_token` (`token_hash`),\n  KEY `idx_invitations_expires` (`expires_at`),\n  CONSTRAINT `fk_invitations_invited_by` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `labels` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `ref_number` int NOT NULL,\n  `ref_string` varchar(255) NOT NULL,\n  `type` varchar(100) NOT NULL,\n  `payload_json` text,\n  `created_by` int NOT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  `source_location_id` int DEFAULT NULL,\n  `destination_location_id` int DEFAULT NULL,\n  `cable_type_id` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_ref_number` (`site_id`,`ref_number`),\n  UNIQUE KEY `unique_site_ref_string` (`site_id`,`ref_string`),\n  KEY `idx_labels_site_id` (`site_id`),\n  KEY `idx_labels_created_by` (`created_by`),\n  KEY `idx_labels_ref_string` (`ref_string`),\n  KEY `idx_labels_source_location_id` (`source_location_id`),\n  KEY `idx_labels_destination_location_id` (`destination_location_id`),\n  KEY `idx_labels_cable_type_id` (`cable_type_id`),\n  CONSTRAINT `fk_labels_cable_type` FOREIGN KEY (`cable_type_id`) REFERENCES `cable_types` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_labels_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_labels_destination_location` FOREIGN KEY (`destination_location_id`) REFERENCES `site_locations` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_labels_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_labels_source_location` FOREIGN KEY (`source_location_id`) REFERENCES `site_locations` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `password_reset_tokens` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `user_id` int NOT NULL,\n  `token_hash` varchar(255) NOT NULL,\n  `expires_at` timestamp(3) NOT NULL,\n  `used_at` timestamp(3) NULL DEFAULT NULL,\n  `created_by_user_id` int DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `token_hash` (`token_hash`),\n  KEY `fk_password_reset_tokens_created_by` (`created_by_user_id`),\n  KEY `idx_password_reset_tokens_user_id` (`user_id`),\n  KEY `idx_password_reset_tokens_token_hash` (`token_hash`),\n  KEY `idx_password_reset_tokens_expires_at` (`expires_at`),\n  CONSTRAINT `fk_password_reset_tokens_created_by` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_password_reset_tokens_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_activity_log` (\n  `id` bigint NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `sid_id` int NOT NULL,\n  `actor_user_id` int NOT NULL,\n  `action` varchar(100) NOT NULL,\n  `summary` varchar(500) NOT NULL,\n  `diff_json` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  KEY `fk_sid_activity_log_actor` (`actor_user_id`),\n  KEY `idx_sid_activity_log_sid_created` (`sid_id`,`created_at`),\n  KEY `idx_sid_activity_log_site_created` (`site_id`,`created_at`),\n  CONSTRAINT `fk_sid_activity_log_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_activity_log_sid` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_activity_log_site` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_connections` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `sid_id` int NOT NULL,\n  `nic_id` int DEFAULT NULL,\n  `switch_sid_id` int NOT NULL,\n  `switch_port` varchar(255) NOT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_switch_port_in_site` (`site_id`,`switch_sid_id`,`switch_port`),\n  KEY `fk_sid_connections_nic_id` (`nic_id`),\n  KEY `fk_sid_connections_switch_sid_id` (`switch_sid_id`),\n  KEY `idx_sid_connections_sid_id` (`sid_id`),\n  CONSTRAINT `fk_sid_connections_nic_id` FOREIGN KEY (`nic_id`) REFERENCES `sid_nics` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sid_connections_sid_id` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_connections_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_connections_switch_sid_id` FOREIGN KEY (`switch_sid_id`) REFERENCES `sids` (`id`) ON DELETE RESTRICT\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_cpu_models` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `manufacturer` varchar(255) DEFAULT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  `cpu_cores` int DEFAULT NULL,\n  `cpu_threads` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_cpu_model_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_cpu_models_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_device_models` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `manufacturer` varchar(255) DEFAULT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `is_switch` tinyint(1) NOT NULL DEFAULT '0',\n  `default_switch_port_count` int DEFAULT NULL,\n  `is_patch_panel` tinyint(1) NOT NULL DEFAULT '0',\n  `default_patch_panel_port_count` int DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_device_model_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_device_models_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_ip_addresses` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `sid_id` int NOT NULL,\n  `ip_address` varchar(64) NOT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_sid_ip_address` (`sid_id`,`ip_address`),\n  CONSTRAINT `fk_sid_ip_addresses_sid_id` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_nic_speeds` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_sid_nic_speed_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_nic_speeds_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_nic_types` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_sid_nic_type_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_nic_types_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_nics` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `sid_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `mac_address` varchar(64) DEFAULT NULL,\n  `ip_address` varchar(64) DEFAULT NULL,\n  `site_vlan_id` int DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  `card_name` varchar(255) DEFAULT NULL,\n  `nic_type_id` int DEFAULT NULL,\n  `nic_speed_id` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `fk_sid_nics_site_vlan_id` (`site_vlan_id`),\n  KEY `idx_sid_nics_sid_id` (`sid_id`),\n  KEY `fk_sid_nics_nic_type_id` (`nic_type_id`),\n  KEY `fk_sid_nics_nic_speed_id` (`nic_speed_id`),\n  CONSTRAINT `fk_sid_nics_nic_speed_id` FOREIGN KEY (`nic_speed_id`) REFERENCES `sid_nic_speeds` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sid_nics_nic_type_id` FOREIGN KEY (`nic_type_id`) REFERENCES `sid_nic_types` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sid_nics_sid_id` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_nics_site_vlan_id` FOREIGN KEY (`site_vlan_id`) REFERENCES `site_vlans` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_notes` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `sid_id` int NOT NULL,\n  `created_by` int DEFAULT NULL,\n  `type` varchar(16) NOT NULL DEFAULT 'NOTE',\n  `note_text` text NOT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `pinned` tinyint(1) NOT NULL DEFAULT '0',\n  `pinned_at` timestamp(3) NULL DEFAULT NULL,\n  `pinned_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `idx_sid_notes_sid_id` (`sid_id`),\n  KEY `idx_sid_notes_sid_pinned` (`sid_id`,`pinned`,`pinned_at`,`created_at`),\n  KEY `fk_sid_notes_created_by` (`created_by`),\n  CONSTRAINT `fk_sid_notes_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sid_notes_sid_id` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_password_types` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` varchar(5000) DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_sid_password_types_site_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_password_types_site` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_passwords` (\n  `sid_id` int NOT NULL,\n  `password_type_id` int NOT NULL,\n  `username` varchar(255) DEFAULT NULL,\n  `password_ciphertext` text,\n  `password_updated_by` int DEFAULT NULL,\n  `password_updated_at` timestamp(3) NULL DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`sid_id`,`password_type_id`),\n  KEY `fk_sid_passwords_updated_by` (`password_updated_by`),\n  KEY `idx_sid_passwords_type` (`password_type_id`),\n  CONSTRAINT `fk_sid_passwords_sid` FOREIGN KEY (`sid_id`) REFERENCES `sids` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_passwords_type` FOREIGN KEY (`password_type_id`) REFERENCES `sid_password_types` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_sid_passwords_updated_by` FOREIGN KEY (`password_updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_platforms` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_platform_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_platforms_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_statuses` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_sid_status_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_statuses_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sid_types` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_sid_type_name` (`site_id`,`name`),\n  CONSTRAINT `fk_sid_types_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sids` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `sid_number` varchar(64) NOT NULL,\n  `sid_type_id` int DEFAULT NULL,\n  `device_model_id` int DEFAULT NULL,\n  `cpu_model_id` int DEFAULT NULL,\n  `hostname` varchar(255) DEFAULT NULL,\n  `serial_number` varchar(255) DEFAULT NULL,\n  `status` varchar(64) DEFAULT NULL,\n  `cpu_count` int DEFAULT NULL,\n  `cpu_cores` int DEFAULT NULL,\n  `cpu_threads` int DEFAULT NULL,\n  `ram_gb` decimal(10,3) DEFAULT NULL,\n  `os_name` varchar(255) DEFAULT NULL,\n  `os_version` varchar(255) DEFAULT NULL,\n  `mgmt_ip` varchar(64) DEFAULT NULL,\n  `mgmt_mac` varchar(64) DEFAULT NULL,\n  `location_id` int DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  `rack_u` varchar(16) DEFAULT NULL,\n  `platform_id` int DEFAULT NULL,\n  `pdu_power` varchar(255) DEFAULT NULL,\n  `switch_port_count` int DEFAULT NULL,\n  `primary_ip` varchar(64) DEFAULT NULL,\n  `subnet_ip` varchar(64) DEFAULT NULL,\n  `gateway_ip` varchar(64) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_sid_number` (`site_id`,`sid_number`),\n  KEY `fk_sids_sid_type_id` (`sid_type_id`),\n  KEY `fk_sids_device_model_id` (`device_model_id`),\n  KEY `fk_sids_cpu_model_id` (`cpu_model_id`),\n  KEY `fk_sids_location_id` (`location_id`),\n  KEY `idx_sids_site_id` (`site_id`),\n  KEY `idx_sids_sid_number` (`sid_number`),\n  KEY `idx_sids_hostname` (`hostname`),\n  KEY `idx_sids_rack_u` (`rack_u`),\n  KEY `idx_sids_platform_id` (`platform_id`),\n  CONSTRAINT `fk_sids_cpu_model_id` FOREIGN KEY (`cpu_model_id`) REFERENCES `sid_cpu_models` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sids_device_model_id` FOREIGN KEY (`device_model_id`) REFERENCES `sid_device_models` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sids_location_id` FOREIGN KEY (`location_id`) REFERENCES `site_locations` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sids_platform_id` FOREIGN KEY (`platform_id`) REFERENCES `sid_platforms` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sids_sid_type_id` FOREIGN KEY (`sid_type_id`) REFERENCES `sid_types` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `fk_sids_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `site_counters` (\n  `site_id` int NOT NULL,\n  `next_ref` int NOT NULL,\n  `next_sid` int NOT NULL DEFAULT '1',\n  PRIMARY KEY (`site_id`),\n  CONSTRAINT `fk_site_counters_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `site_locations` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `floor` varchar(50) NOT NULL,\n  `suite` varchar(50) DEFAULT NULL,\n  `row` varchar(50) DEFAULT NULL,\n  `rack` varchar(50) DEFAULT NULL,\n  `label` varchar(255) DEFAULT NULL,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  `label_key` varchar(255) GENERATED ALWAYS AS (ifnull(nullif(trim(`label`),_utf8mb4''),_utf8mb4'__UNLABELED__')) STORED,\n  `template_type` enum('DATACENTRE','DOMESTIC') NOT NULL DEFAULT 'DATACENTRE',\n  `area` varchar(64) DEFAULT NULL,\n  `suite_key` varchar(50) GENERATED ALWAYS AS (ifnull(nullif(trim(`suite`),_utf8mb4''),_utf8mb4'__NONE__')) STORED,\n  `row_key` varchar(50) GENERATED ALWAYS AS (ifnull(nullif(trim(`row`),_utf8mb4''),_utf8mb4'__NONE__')) STORED,\n  `rack_key` varchar(50) GENERATED ALWAYS AS (ifnull(nullif(trim(`rack`),_utf8mb4''),_utf8mb4'__NONE__')) STORED,\n  `area_key` varchar(64) GENERATED ALWAYS AS (ifnull(nullif(trim(`area`),_utf8mb4''),_utf8mb4'__NONE__')) STORED,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `idx_site_locations_unique_identity` (`site_id`,`template_type`,`floor`,`suite_key`,`row_key`,`rack_key`,`area_key`,`label_key`),\n  KEY `idx_site_locations_site_id` (`site_id`),\n  CONSTRAINT `fk_site_locations_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `site_memberships` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `user_id` int NOT NULL,\n  `site_role` varchar(50) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_user` (`site_id`,`user_id`),\n  KEY `idx_site_memberships_site_id` (`site_id`),\n  KEY `idx_site_memberships_user_id` (`user_id`),\n  KEY `idx_site_memberships_role` (`site_role`),\n  CONSTRAINT `fk_site_memberships_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_site_memberships_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `site_vlans` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `site_id` int NOT NULL,\n  `vlan_id` int NOT NULL,\n  `name` varchar(255) NOT NULL,\n  `description` text,\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_site_vlan_id` (`site_id`,`vlan_id`),\n  CONSTRAINT `fk_site_vlans_site_id` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `sites` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `name` varchar(255) NOT NULL,\n  `code` varchar(255) NOT NULL,\n  `created_by` int NOT NULL,\n  `location` varchar(500) DEFAULT NULL,\n  `description` text,\n  `is_active` tinyint(1) NOT NULL DEFAULT '1',\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`code`),\n  KEY `idx_sites_created_by` (`created_by`),\n  KEY `idx_sites_active` (`is_active`),\n  KEY `idx_sites_name` (`name`),\n  KEY `idx_sites_code` (`code`),\n  CONSTRAINT `fk_sites_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `user_activity` (\n  `user_id` int NOT NULL,\n  `last_activity` timestamp(3) NULL DEFAULT NULL,\n  `last_login` timestamp(3) NULL DEFAULT NULL,\n  PRIMARY KEY (`user_id`),\n  KEY `idx_user_activity_last_activity` (`last_activity`),\n  KEY `idx_user_activity_last_login` (`last_login`),\n  CONSTRAINT `fk_user_activity_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
      await adapter.execute("CREATE TABLE `users` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `email` varchar(255) NOT NULL,\n  `password_hash` varchar(255) NOT NULL,\n  `username` varchar(255) NOT NULL,\n  `role` varchar(50) NOT NULL DEFAULT 'USER',\n  `is_active` tinyint(1) NOT NULL DEFAULT '1',\n  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `email` (`email`),\n  KEY `idx_users_email` (`email`),\n  KEY `idx_users_active` (`is_active`),\n  KEY `idx_users_role` (`role`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    } finally {
      await adapter.execute('SET FOREIGN_KEY_CHECKS = 1');
    }
  },
  down: async (adapter) => {
    // Not intended for production rollback; provided for completeness.
    await adapter.execute('SET FOREIGN_KEY_CHECKS = 0');
    try {
      await adapter.execute("DROP TABLE IF EXISTS `users`");
      await adapter.execute("DROP TABLE IF EXISTS `user_activity`");
      await adapter.execute("DROP TABLE IF EXISTS `sites`");
      await adapter.execute("DROP TABLE IF EXISTS `site_vlans`");
      await adapter.execute("DROP TABLE IF EXISTS `site_memberships`");
      await adapter.execute("DROP TABLE IF EXISTS `site_locations`");
      await adapter.execute("DROP TABLE IF EXISTS `site_counters`");
      await adapter.execute("DROP TABLE IF EXISTS `sids`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_types`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_statuses`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_platforms`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_passwords`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_password_types`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_notes`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_nics`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_nic_types`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_nic_speeds`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_ip_addresses`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_device_models`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_cpu_models`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_connections`");
      await adapter.execute("DROP TABLE IF EXISTS `sid_activity_log`");
      await adapter.execute("DROP TABLE IF EXISTS `password_reset_tokens`");
      await adapter.execute("DROP TABLE IF EXISTS `labels`");
      await adapter.execute("DROP TABLE IF EXISTS `invitations`");
      await adapter.execute("DROP TABLE IF EXISTS `invitation_sites`");
      await adapter.execute("DROP TABLE IF EXISTS `cable_types`");
      await adapter.execute("DROP TABLE IF EXISTS `app_settings`");
      await adapter.execute("DROP TABLE IF EXISTS `activity_log`");
    } finally {
      await adapter.execute('SET FOREIGN_KEY_CHECKS = 1');
    }
  },
};
